### ISSUE TITLE
FR: Large payloads

### ISSUE THREAD

**Issue by bertmelis** [philbowles/PangolinMQTT#1]
Feature request: Do you think you would ever implement reception of large payloads (even only QoS 0)?

I prefer to implement only one interface on my ESPs to interact with I would like to have OTA over MQTT.

**Comment by philbowles** [comment]
Depends what you mean by "large" - it can already handle up to ~20kb on ESP8266 and ~120kb on ESP32

**Comment by bertmelis** [comment]
ESP's firmware is about 500kB. So it definitely doesn't fit in memory.

Now the issue is off course that this doesn't fit into the current API. And I didn't look into the source to see if it is even possible to do it elegantly.
