### ISSUE TITLE
Pangolin.....

### ISSUE THREAD

**Issue by leifclaesson** [philbowles/PangolinMQTT#11]
This is not an issue. Just thought I'd show my appreciation and offer some encouragement.

![image](https://user-images.githubusercontent.com/775408/87552005-4ff7d180-c6db-11ea-8df8-5109e9c42d58.png)

o_O

As you can imagine, this is NOT something that ever happened with AsyncMqttClient... MQTT uptime equal to WiFi uptime?? Yeah, that never happened before.

Nice one, mate.

**Comment by leifclaesson** [comment]
I know, I'm starting to sound like a sycophant, but when you've lived with AsyncMqttClient for a year, you learn to appreciate the little things.

![image](https://user-images.githubusercontent.com/775408/87633785-351e6f00-c766-11ea-998c-4f357e3c89c5.png)

**Comment by philbowles** [comment]
Your appreciation is appreciated :) Spread the word. Pangolin was expressly written to save the world from "the other library"

**Comment by luebbe** [comment]
I'm a bit torn between trying to port https://github.com/homieiot/homie-esp8266 to pangolin so that everyone working with homie can benefit or switching my own stuff to https://github.com/leifclaesson/LeifHomieLib, since you have already done a part of the work.
Needless to say that homie-esp8266 was originally written by the author of "the other library", so I'm not sure what to expect. :-)

**Comment by leifclaesson** [comment]
That sounds like a dilemma, Luebbe :).

I'm very much an "if it ain't broken, don't fix it" kind of guy, with nowhere near enough free time to maintain existing things if they're already working, so there's a distinct possibility that homie-esp8266 will see more updates in the future than LeifHomieLib. Also, my programming style may be unorthodox so it may be significant work to port from one library to the other. That said, I do use it myself (obviously) and now that it uses Pangolin, it appears to be 100% stable. There's plenty of mitigation code still there, originally written to not overload the.. other library, but it doesn't seem to be hurting anything, and perhaps it's a good thing that it's throttling itself


Hey Phil, how did you come up with the Pangolin name? What does it mean? I'm kinda regretting my library name choice and wondering whether maybe I ought to rename LeifHomieLib to something more universally applicable.

**Comment by philbowles** [comment]
Re the name: I have been using - and fixing, and diagnosing and patching other peoples libraries on esp8266 for a few years now, just to get my own firmware to run! Examples I have fixed are: Arduino core (wstring bug),3x bugs in ESPAsyncWebserver, ESPAsyncTCP,  STM32Duino, etc etc...so in *my*  experience, a *solid* esp8266 library is a rare beast.

Google then showed me that the rarest beast on the planet is the pangolin, and I liked the logo. :)

**Comment by leifclaesson** [comment]
Okay, it could have been great.. I gave up due to lack of activity, it seemed great in the beginning but it didn't last, and the issues I came across were impossible to work around...
