### ISSUE TITLE
Typo Quickfix: resued should be?

### ISSUE THREAD

**Issue by pfeerick** [philbowles/PangolinMQTT#16]
On line 46 of https://github.com/philbowles/PangolinMQTT/blob/master/docs/bugs.md#major-flaw-1-mf1-the-dangling-pointer:

>  data is often still in the same place and has not yet been overwritten/resued when LwIP decides to send it

resued?

**Comment by philbowles** [comment]
Thank you, well spotted! There are probably dozens of others too. :(

**Comment by pfeerick** [comment]
No problem... PR #15 will resolve most of them - I just wasn't sure what exactly you were saying there... hence a quick fix ;) btw, it is better to use githubs automation and close issues by simply saying 'Closes #issuenum/Fixes #issuenum' in the commit message of the commit that resolves it... you won't get stale issues, or close an issue without addressing the problem raised, unless it's a wontfix or PBKAC error.
