### ISSUE TITLE
Disconnected from MQTT

### ISSUE THREAD

**Issue by juanitoddd** [philbowles/PangolinMQTT#23]
Hello, first of all, thanks for this library !

I am able to run QuickStart_P  on a NodeMCU Esp8266 and connect to Wifi/Mqtt

After some minutes though, the client disconnects showing:

`Disconnected from MQTT reason=-13`

And then it does not reconnect at all

If you could point me out where to find more about this reason -13, I would thank you greatly

**Comment by serek4** [comment]
negative reason is lwip error.
[esp8266 core 2.7.4 lwip errors](https://github.com/esp8266/Arduino/blob/2.7.4/tools/sdk/lwip/include/lwip/err.h)
`define ERR_USE        -13   /* Address in use.          */`
[esp8266 core 2.7.4 lwip2 errors](https://github.com/esp8266/Arduino/blob/2.7.4/tools/sdk/lwip2/include/lwip/err.h)
`/** Connection aborted.      */
  ERR_ABRT       = -13,`

**Comment by mrohner** [comment]
I get same error with the sample A code. This is with ESP8266 core 2.4.2
T=44246 Message domoticz/in qos0 dup=0 retain=0 len=35 elapsed=36350
{"idx":84,"nvalue":0,"svalue":"11"}
T=45559 Message domoticz/in qos0 dup=0 retain=0 len=34 elapsed=37663
{"idx":85,"nvalue":0,"svalue":"5"}
T=46903 Message domoticz/in qos0 dup=0 retain=0 len=33 elapsed=39007
{"idx":24,"nvalue":1,"svalue":""}
T=47003 Message domoticz/in qos0 dup=0 retain=0 len=33 elapsed=39107
{"idx":25,"nvalue":1,"svalue":""}
T=47700 Message domoticz/in qos0 dup=0 retain=0 len=35 elapsed=39804
{"idx":86,"nvalue":0,"svalue":"16"}
T=49344 Message domoticz/in qos0 dup=0 retain=0 len=34 elapsed=41448
{"idx":83,"nvalue":0,"svalue":"8"}
T=49559 Message domoticz/in qos0 dup=0 retain=0 len=35 elapsed=41663
{"idx":82,"nvalue":0,"svalue":"13"}
T=71695 Message domoticz/in qos0 dup=0 retain=0 len=38 elapsed=63799
{"idx": 47,"nvalue": 1,"svalue":"969"}
T=71932 Message domoticz/in qos0 dup=0 retain=0 len=34 elapsed=64036
{"idx": 51,"nvalue":0,"svalue":""}
T=72693 Message domoticz/in qos0 dup=0 retain=0 len=33 elapsed=64797
{"idx":55,"nvalue":0,"svalue":""}
T=86856 Message domoticz/in qos0 dup=0 retain=0 len=34 elapsed=78960
{"idx":35,"nvalue":1,"svalue":"0"}
T=86909 Message domoticz/in qos0 dup=0 retain=0 len=34 elapsed=79013
{"idx":34,"nvalue":0,"svalue":"0"}
T=86928 Message domoticz/in qos0 dup=0 retain=0 len=44 elapsed=79032
{"idx":33,"nvalue":0,"svalue":"23.1;38.7;1"}
T=87380 Message domoticz/in qos0 dup=0 retain=0 len=34 elapsed=79484
{"idx":13,"nvalue":1,"svalue":"0"}
T=87439 Message domoticz/in qos0 dup=0 retain=0 len=35 elapsed=79543
{"idx":15,"nvalue":1,"svalue":"95"}
T=87679 Message domoticz/in qos0 dup=0 retain=0 len=34 elapsed=79783
{"idx":14,"nvalue":0,"svalue":"0"}
T=98804 Message domoticz/in qos0 dup=0 retain=0 len=47 elapsed=90908
{"parse":false,"idx":56,"nvalue":1,"svalue":""}
T=98905 Message domoticz/in qos0 dup=0 retain=0 len=34 elapsed=91009
{"idx":90,"nvalue":0,"svalue":"0"}
T=98905 Message domoticz/in qos0 dup=0 retain=0 len=44 elapsed=91009
{"idx":91,"nvalue":0,"svalue":"24.7;45.2;1"}
T=104198 Message domoticz/in qos0 dup=0 retain=0 len=35 elapsed=96302
{"idx":84,"nvalue":0,"svalue":"10"}
T=105435 Message domoticz/in qos0 dup=0 retain=0 len=35 elapsed=97539
{"idx":85,"nvalue":0,"svalue":"12"}
T=107194 Message domoticz/in qos0 dup=0 retain=0 len=33 elapsed=99298
{"idx":24,"nvalue":1,"svalue":""}
T=107296 Message domoticz/in qos0 dup=0 retain=0 len=33 elapsed=99400
{"idx":25,"nvalue":1,"svalue":""}
T=107572 Message domoticz/in qos0 dup=0 retain=0 len=35 elapsed=99676
{"idx":86,"nvalue":0,"svalue":"20"}
T=109193 Message domoticz/in qos0 dup=0 retain=0 len=34 elapsed=101297
{"idx":83,"nvalue":0,"svalue":"7"}
T=109404 Message domoticz/in qos0 dup=0 retain=0 len=35 elapsed=101508
{"idx":82,"nvalue":0,"svalue":"12"}
Disconnected from MQTT reason=1
Connecting to MQTT...
Disconnected from MQTT reason=-13
Connecting to MQTT...
Disconnected from MQTT reason=-13
Connecting to MQTT...


The log says:
            14:24:52 Ubuntu mosquitto[813]: 1604064292: New client connected from 192.168.178.47 as StonelampTest (p2, c1, k30, u'mqtt').
Oct 30 14:24:52 Ubuntu mosquitto[813]: New client connected from 192.168.178.47 as StonelampTest (p2, c1, k30, u'mqtt').
Oct 30 14:28:13 Ubuntu mosquitto[813]: 1604064493: Client StonelampTest has exceeded timeout, disconnecting.
Oct 30 14:28:13 Ubuntu mosquitto[813]: Client StonelampTest has exceeded timeout, disconnecting.

**Comment by philbowles** [comment]
Let me know if problems persist in latest release 1.0.0
