### ISSUE TITLE
Question om MQTT user and PW

### ISSUE THREAD

**Issue by mrohner** [philbowles/PangolinMQTT#25]
There seems to be no keyword file. How to set mqtt user and Password please?

**Comment by AcuarioCat** [comment]
#define MQTT_USER "MY_USERNAME"
#define MQTT_PASS "MY_PASSWORD"

PangolinMQTT mqttClient;
mqttClient.setCredentials(MQTT_USER, MQTT_PASS);

etc....

**Comment by mrohner** [comment]
Thanks
