### ISSUE TITLE
Reason for restriction of TLS support to ESP8266?

### ISSUE THREAD

**Issue by matthias-bs** [philbowles/PangolinMQTT#43]
Hi,

is there a technical reason for restricting TLS support to ESP8266? It would be great to have this for ESP32, too.

Thanks in advance!

Best regards
Matthias

**Comment by HamzaHajeir** [comment]
Hi matthias, 

I'm not very aware of why it's restricted, maybe the author didn't find a way to.

but overall, I'm sad to inform you the the author has passed away 5 months ago, I hope someone could find a way to get it running.

**Comment by luebbe** [comment]
That is sad to hear. 
@matthias-bs maybe take a look at https://github.com/bertmelis/espMqttClient? It claims to support TLS using standard wifi client secure connections. I'm using it in one of my projects, but without TLS.

**Comment by matthias-bs** [comment]
Oh, this is indeed sad news.

Thanks a lot for your feedback.

**Comment by HamzaHajeir** [comment]
You're welcome,

We the people near to Phil (over the internet) would try to get his
paperworks, he had developed a new AsyncTCP library (unpublished still),
and it would be our starting point to reflect it to other libraries within
the h4plugins project.

Something to pay back for him.


Talking about TLS issue, I think an expert could port it out to ESP32, it's
a matter of APIs utilization as I can imagine.

**Comment by HamzaHajeir** [comment]
TLS is supported in ESP32, please check the [forked library](https://github.com/hamzahajeir/h4asyncmqtt).
