### ISSUE TITLE
_cbPublish callback is called twice

### ISSUE THREAD

**Issue by Pablo2048** [philbowles/PangolinMQTT#6]
Hi Phill,
thank You for taking the lead and trying to do Async MQTT client library. When switching from AsyncMqttClient i discovered, that the `onPublish` callback is called twice. Maybe it is just an typo here https://github.com/philbowles/PangolinMQTT/blob/ff68b5ff114d35c5b873da02e9761f91fafda15f/src/PangolinMQTT.cpp#L196 or here https://github.com/philbowles/PangolinMQTT/blob/ff68b5ff114d35c5b873da02e9761f91fafda15f/src/PangolinMQTT.cpp#L200

**Comment by philbowles** [comment]
Yes, its a silly error by me :( Also been spotted already and is fixed in the current dev branch if you'd like to try it there - that branch also fixes some ESP32 problems.

And thank *you* for your support.
