### ISSUE TITLE
Compile errors with NO_GLOBAL_SERIAL defined due to Serial.printf vs PANGO_PRINT

### ISSUE THREAD

**Issue by leifclaesson** [philbowles/PangolinMQTT#8]
A few places in both PANGO.cpp and PangolinMQTT.cpp reference Serial directly, rather than PANGO_PRINT, which fails due to Serial not being defined if a project is compiled with NO_GLOBAL_SERIAL, commonly used when you run out of pins on the ESP8266 and need to reuse the serial port pins. :)

I realize the library is in alpha-state so it's probably way too early for a pull request -- figured I'd just mentioned it here instead.

**Comment by philbowles** [comment]
Thanks for this I will look at excluding any Serials if NO_GLOBAL_SERIAL is defined

**Comment by leifclaesson** [comment]
Ah! I get it now. I hadn't considered that it might be _intentional_, to let certain error messages through even when not debugging.

In that case, may I suggest an alternative solution -- PANGO_PRINT with a severity level?

Because, in my own projects, even on projects where I've set NO_GLOBAL_SERIAL, I still have debug console output through _telnet_. If you make a lambda hook for critical messages, I'll hook it to my console so that I'll see them.

**Comment by philbowles** [comment]
Yes, you got it...dumphex is always available (even when not in debug mode), as it shows the contents of the packet.  It is a simple job to #ifdef that out though.
